my-app {
  routes {
    ask-timeout = 5s
    myport = 8081
    user-service = "http://localhost:8080/users/"
    wallet-service = "http://localhost:8082/wallets/"
  }
}

akka {
  actor {
    provider = "cluster"

    serializers {
      jackson-json = "akka.serialization.jackson.JacksonJsonSerializer"
    }

    serialization-bindings {

      "com.example.ImportantActors.Oneproduct$Command" = jackson-json
      "com.example.ImportantActors.Oneproduct$GetProductDetails" = jackson-json
      "com.example.Responses.ProductFound" = jackson-json
        "com.example.SerializableTraitClass" = jackson-json

    }
  }

  remote {
    artery {
      enabled = on
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = 25251
      security {
        allow-serialization-of-serializable = on
      }
    }
  }

  cluster {
    seed-nodes = [
      "akka://ClusterSystem@127.0.0.1:8083"
    ]

    sharding {
      least-shard-allocation-strategy {
              rebalance-threshold = 999999  # Effectively disable rebalance threshold
              rebalance-interval = 999999  # Disable rebalance interval
              max-simultaneous-rebalance = 0  # Disable all simultaneous rebalancing
              rebalance-absolute-limit = 0

                  # Maximum number of shards that will be rebalanced in one rebalance round.
                  # Fraction of total number of (known) shards.
                  # The lower of this and `rebalance-absolute-limit` will be used.
              rebalance-relative-limit = 0.1
            }
      passivation {
        strategy = none
      }
    }
  }
}
