my-app {
  routes {
    # If ask takes more time than this to complete, the request fails
    ask-timeout = 5s
    myport = 8080
    user-service = "http://host.docker.internal:8080/users/"
    wallet-service = "http://host.docker.internal:8082/wallets/"
  }
}

akka {
  actor {
    provider = "cluster"

    serializers {
      jackson-json = "akka.serialization.jackson.JacksonJsonSerializer"
    }

    serialization-identifiers {
      jackson-json = 9999  # Unique integer ID
    }

    serialization-bindings {
      "java.io.Serializable" = jackson-json
    }
  }

  remote {
    artery {
      enabled = on
      transport = tcp
      canonical.hostname = "127.0.0.1"  # IP address for the node in the cluster
      canonical.port = 25251            # Internal port for cluster communication
    }
  }

  cluster {
    seed-nodes = [
      "akka://GatewaySystem@127.0.0.1:25251"
    ]

    sharding {
      passivation {
        strategy = none
      }
    }
  }
}
