my-app {
  routes {
    ask-timeout = 5s
    myport = 8081
    user-service = "http://localhost:8080/users/"
    wallet-service = "http://localhost:8082/wallets/"
  }
}

akka {
  actor {
    provider = "cluster"

    serializers {
      jackson-json = "akka.serialization.jackson.JacksonJsonSerializer"
    }

    serialization-bindings {

      "com.example.ImportantActors.Oneproduct$Command" = jackson-json
      "com.example.ImportantActors.Oneproduct$GetProductDetails" = jackson-json
      "com.example.Responses.ProductFound" = jackson-json
        "com.example.SerializableTraitClass" = jackson-json

    }
  }

  remote {
    artery {
      enabled = on
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = 25251
      security {
        allow-serialization-of-serializable = on
      }
    }
  }

  cluster {
    seed-nodes = [
      "akka://ClusterSystem@127.0.0.1:8083"
    ]

    sharding {
      passivation {
        strategy = none
      }
    }
  }
}
