spring.application.name=demo_onlycrud

# spring.datasource.url=jdbc:mysql://10.24.48.61:3306/onlinemarketplace?useSSL=false
# spring.datasource.username=sailaptop
# spring.datasource.password=my_new_password

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
server.port=8080
